-- This file is automatic generated and changes are not be reflected in future updates
-- ID, Text_lang, SortIndex, Min_level, Max_level
GameTips = {
	{ 201, "|cffffd100Tip:|r Your spell casting can be cancelled by moving, jumping or hitting the escape key. \n  \n ", 1, 0, 60 },
	{ 221, "|cffffd100Tip:|r Clicking on a player name in the chat window lets you send a private message to them. \n ", 2, 0, 60 },
	{ 222, "|cffffd100Tip:|r You can <Control>Click on an item to see how you would look wearing that item. \n ", 4, 0, 60 },
	{ 223, "|cffffd100Tip:|r An item with its name in gray is a poor quality item and in most cases it can be sold to a vendor. \n ", 5, 0, 60 },
	{ 224, "|cffffd100Tip:|r An item with its name in white is useful to players in some way and can be used or sold in the auction house. \n ", 6, 0, 60 },
	{ 225, "|cffffd100Tip:|r You can send mail to other players or even to your other characters from any mailbox in game. \n ", 8, 0, 60 },
	{ 226, "|cffffd100Tip:|r You can <Shift>Click on an item to place an item link into a chat message. \n ", 9, 0, 60 },
	{ 227, "|cffffd100Tip:|r All of your action bars can have their hotkeys remapped in the key bindings interface. \n ", 12, 0, 60 },
	{ 228, "|cffffd100Tip:|r If a profession trainer cannot teach you any more, they will generally tell you where to go to get further training. \n ", 13, 0, 60 },
	{ 229, "|cffffd100Tip:|r On your character sheet is a reputation tab that tells you your status with different groups. \n ", 14, 0, 60 },
	{ 230, "|cffffd100Tip:|r You can perform many fun actions with the emote system, for instance you can type /dance to dance. \n ", 17, 0, 60 },
	{ 231, "|cffffd100Tip:|r The interface options menu <ESC> has lots of ways to customize your game play. \n ", 21, 0, 60 },
	{ 232, "|cffffd100Tip:|r You can turn off the slow scrolling of quest text in the interface options menu. \n  \n ", 22, 0, 60 },
	{ 233, "|cffffd100Tip:|r Spend your talent points carefully as once your talents are chosen, you must spend gold to unlearn them. \n ", 23, 0, 60 },
	{ 234, "|cffffd100Tip:|r A mail icon next to the minimap means you have new mail.  Visit a mailbox to retrieve it. \n ", 24, 0, 60 },
	{ 235, "|cffffd100Tip:|r You can add additional action bars to your game interface from the interface options menu. \n ", 25, 0, 60 },
	{ 236, "|cffffd100Tip:|r If you hold down <Shift> while right-clicking on a target to loot, you will automatically loot all items on the target. \n ", 26, 0, 60 },
	{ 237, "|cffffd100Tip:|r If you enjoyed playing with someone, put them on your friends list! \n ", 28, 0, 60 },
	{ 239, "|cffffd100Tip:|r There are a number of different loot options when in a group.   The group leader can right-click their own portrait to change the options. \n ", 30, 0, 60 },
	{ 240, "|cffffd100Tip:|r You can choose not to display your helm and/or cloak with an option from the interface options menu. \n ", 31, 0, 60 },
	{ 241, "|cffffd100Tip:|r You can target members of your party with the function keys.   F1 targets you; F2 targets the second party member. \n ", 32, 0, 60 },
	{ 242, "|cffffd100Tip:|r Being polite while in a group with others will get you invited back!", 33, 0, 60 },
	{ 243, "|cffffd100Tip:|r When in a queue for a battleground you don't need to wait by the battleground to stay in the queue. \n ", 35, 0, 60 },
	{ 244, "|cffffd100Tip:|r A monster with a silver dragon around its portrait is a rare monster with better than average treasure. \n ", 36, 0, 60 },
	{ 245, "|cffffd100Tip:|r If you mouse over a chat pane it will become visible and you can right-click on the chat pane tab for options. \n ", 37, 0, 60 },
	{ 246, "|cffffd100Tip:|r You can display the duration of beneficial spells on you from the interface options menu. \n ", 39, 0, 60 },
	{ 247, "|cffffd100Tip:|r You can lock your action bar so you don't accidentally move spells.  This is done using the interface options menu. \n ", 40, 0, 60 },
	{ 248, "|cffffd100Tip:|r You can cast a spell on yourself without deselecting your current target by holding down <Alt> while pressing your hotkey. \n ", 42, 0, 60 },
	{ 249, "|cffffd100Tip:|r Killing Civilians will give you a dishonorable kill and an honor rating penalty. \n  \n ", 45, 0, 60 },
	{ 250, "|cffffd100Tip:|r Killing guards gives no honor.", 46, 0, 60 },
	{ 251, "|cffffd100Tip:|r Typing /macro will bring up the interface to create macros. \n ", 48, 0, 60 },
	{ 252, "|cffffd100Tip:|r Enemy players whose names appear in gray are much lower level than you are and will not give honor when killed. \n ", 49, 0, 60 },
	{ 253, "|cffffd100Tip:|r When you are in a raid you can drag a group or class type from the raid window to your game field so you can always see their health and mana. \n ", 50, 0, 60 },
	{ 254, "|cffffd100Tip:|r You can hide your interface with <Alt>Z and take screenshots with <Print Screen>. \n ", 47, 0, 60 },
	{ 256, "|cffffd100Tip:|r You can assign a Hotkey to toggle locking/unlocking your action bar.  Just look in the Key Bindings options to set it. \n ", 41, 0, 60 },
	{ 258, "|cffffd100Tip:|r If you <Shift>Click on a player name in the chat window it tells you additional information about them. \n ", 3, 0, 60 },
	{ 261, "|cffffd100Tip:|r  A blue question mark above a quest giver means the quest is repeatable.  \n ", 51, 0, 60 },
	{ 262, "|cffffd100Tip:|r Use the assist button (F key) while targeting another player, and it will target the same target as that player. \n ", 52, 0, 60 },
	{ 263, "|cffffd100Tip:|r You can use the Tab key to select nearby enemies in front of you. \n ", 15, 0, 60 },
	{ 281, "|cffffd100Tip:|r <Shift>Clicking on an item being sold by a vendor will let you select how many of that item you wish to purchase.", 53, 0, 60 },
	{ 282, "|cffffd100Tip:|r When you learn a profession or secondary skill the button that allows you to perform that skill is found in the general tab of your spellbook.", 11, 0, 60 },
	{ 301, "|cffffd100Tip:|r You can right-click on a beneficial spell that has been cast on you to dismiss it. \n ", 20, 0, 60 },
	{ 321, "|cffffd100Tip:|r If you are having trouble finding something in a capital city, try asking a guard for directions. \n ", 16, 0, 60 },
	{ 341, "|cffffd100Tip:|r Remember to take all things in moderation (even World of Warcraft!)", 34, 0, 60 },
	{ 380, "|cffffd100Tip:|r You can view messages you previously sent in chat by pressing <Alt> and the up arrow key.", 56, 0, 60 },
	{ 381, "|cffffd100Tip:|r You can Shift-Click on an item stack to split it into smaller stacks.", 57, 0, 60 },
	{ 382, "|cffffd100Tip:|r Pressing both mouse buttons simultaneously will make your character run.", 58, 0, 60 },
	{ 383, "|cffffd100Tip:|r When replying to a tell from a player (Default 'R'), the <TAB> key cycles through people you have recently replied to.", 59, 0, 60 },
	{ 384, "|cffffd100Tip:|r You can remove a friendly spell enhancement on yourself by right-clicking on the spell effect icon.", 10, 0, 60 },
	{ 387, "|cffffd100Tip:|r A Blizzard employee will NEVER ask for your password.", 18, 0, 60 },
	{ 388, "|cffffd100Tip:|r Clicking an item name that appears bracketed in chat will tell you more about the item. \n ", 60, 0, 60 },
	{ 389, "|cffffd100Tip:|r You can only know two professions at a time, but you can learn all of the secondary skills (fishing, cooking and first-aid).", 19, 0, 60 },
	{ 390, "|cffffd100Tip:|r It's considered polite to talk to someone before inviting them into a group, or opening a trade window.", 61, 0, 60 },
	{ 391, "|cffffd100Tip:|r Pressing 'v' will toggle the display of a health bar over nearby enemies.", 62, 0, 60 },
	{ 392, "|cffffd100Tip:|r Your items do not suffer durability damage when you are killed by an enemy player.", 63, 0, 60 },
	{ 393, "|cffffd100Tip:|r <Shift>click on a quest in your quest log to toggle quest tracking for that quest. \n ", 64, 0, 60 },
	{ 394, "|cffffd100Tip:|r Nearby questgivers that are awaiting your return are shown as a yellow dot on your mini-map. \n ", 67, 0, 60 },
	{ 395, "|cffffd100Tip:|r If you are lost trying to complete a quest, the quest log will often tell you what to do next. \n ", 7, 0, 60 },
	{ 396, "|cffffd100Tip:|r Nearby questgivers that are awaiting your return are shown as a yellow dot on your mini-map. \n ", 0, 0, 60 },
	{ 397, "|cffffd100Tip:|r The auction houses in each of your faction's major cities are linked together.  \n ", 66, 0, 60 },
	{ 398, "|cffffd100Tip:|r Ensure that all party members are on the same stage of an escort quest before beginning it.", 43, 0, 60 },
	{ 399, "|cffffd100Tip:|r Quests completed at maximum level award money instead of experience. \n ", 67, 0, 60 },
	{ 400, "|cffffd100Tip:|r If you are having trouble fishing in an area, try attaching a lure to your fishing pole.", 55, 0, 60 },
	{ 401, "|cffffd100Tip:|r Your character can eat and drink at the same time.", 27, 0, 60 },
	{ 402, "|cffffd100Tip:|r Playing in a battleground on its holiday weekend increases your reputation and honor gained. \n ", 54, 0, 60 },
	{ 403, "|cffffd100Tip:|r <Shift>-B will open all your bags at once.", 68, 0, 60 },
	{ 404, "|cffffd100Tip:|r When interacting with other players a little kindness goes a long way!  \n ", 69, 0, 60 },
	{ 405, "|cffffd100Tip:|r You're much less likely to encounter wandering monsters while following a road.", 44, 0, 60 },
	{ 406, "|cffffd100Tip:|r It is better to quest and die, than never to have quested at all. \n ", 29, 0, 60 },
	{ 407, "|cffffd100Tip:|r Bring your friends to Azeroth, but don't forget to go outside Azeroth with them as well. \n ", 70, 0, 60 },
	{ 409, "|cffffd100Tip:|r If you keep an empty mailbox, the mail icon will let you know when you have new mail waiting! \n ", 71, 0, 60 },
	{ 410, "|cffffd100Tip:|r Never give another player your account information.", 72, 0, 60 },
	{ 411, "|cffffd100Tip:|r Sharing an account with someone else can compromise its security. \n ", 38, 0, 60 },
	{ 412, "|cffffd100Tip:|r You can turn these tips off in the Interface menu.", 73, 0, 60 },
}
