-- This file is automatic generated and changes are not be reflected in future updates
-- 1.13.2.30862
-- ID, Name_lang
SpellFocusObject = {
	{ 1, "Anvil" },
	{ 2, "Loom" },
	{ 3, "Forge" },
	{ 4, "Cooking Fire" },
	{ 5, "Shards of Myzrael" },
	{ 6, "Winterhoof Water Well" },
	{ 7, "Thunderhorn Water Well" },
	{ 8, "Wildmane Water Well" },
	{ 9, "Tribal Fire" },
	{ 10, "Machine Shop" },
	{ 11, "Shadowglen Moonwell" },
	{ 12, "Starbreeze Village Moonwell" },
	{ 13, "Pools of Arlithrien Moonwell" },
	{ 14, "Oracle Glade Moonwell" },
	{ 15, "Venture Co. Airport" },
	{ 16, "Venture Co. Wagon (Blue)" },
	{ 17, "Venture Co. Wagon (Red)" },
	{ 18, "NG-5 Explosives (Red)" },
	{ 19, "NG-5 Explosives (Blue)" },
	{ 20, "Flame of Uzel" },
	{ 21, "Ashenvale Moonwell" },
	{ 22, "Seaworn Altar" },
	{ 23, "Nearby Tubers" },
	{ 43, "Undercity Summoning Circle" },
	{ 63, "Shaman Shrine" },
	{ 83, "Stormwind Summoning Circle" },
	{ 103, "Barrens Summoning Circle" },
	{ 123, "Mirror Lake Waterfall" },
	{ 143, "Talon Den" },
	{ 163, "Xavian Waterfall" },
	{ 164, "Stone of Outer Binding" },
	{ 183, "Mana Rift Disturbance" },
	{ 203, "Orgrimmar Summoning Circle" },
	{ 223, "Ruins of Stardust Fountain" },
	{ 224, "Quilboar Watering Hole" },
	{ 225, "Water Purity - Silverpine" },
	{ 226, "Spring Well" },
	{ 243, "Temple of the Moon Fountain" },
	{ 263, "Jintha'Alor Altar" },
	{ 264, "Pirate Ship Bilge" },
	{ 283, "Equinex Monolith" },
	{ 303, "Witherbark Village" },
	{ 304, "Shadra'Alor Altar" },
	{ 323, "Sandsorrow Watch Water Hole" },
	{ 343, "Hatetalon Stones" },
	{ 363, "Echeyakee's Lair" },
	{ 383, "The Dead Tree" },
	{ 403, "Makeshift Helipad" },
	{ 423, "Circle of Aquementas" },
	{ 424, "Sanctum of the Fallen God" },
	{ 443, "the First Tide Pool" },
	{ 444, "the Second Tide Pool" },
	{ 445, "the Third Tide Pool" },
	{ 446, "the Fourth Tide Pool" },
	{ 463, "Gorishi Hive Hatchery" },
	{ 483, "Miblon Snarltooth" },
	{ 503, "Gadgetzan Graveyard" },
	{ 523, "the ruins of Irontree Woods" },
	{ 543, "Black Forge" },
	{ 563, "Golakka Crater" },
	{ 583, "Tomb of the Seven" },
	{ 603, "Flat Un'Goro Rock" },
	{ 604, "Preserved Threshadon Carcass" },
	{ 623, "Black Anvil" },
	{ 643, "Gorishi Silithid Crystal" },
	{ 644, "Corrupted Moonwell" },
	{ 663, "Alchemy Lab" },
	{ 683, "Unforged Seal of Ascension" },
	{ 703, "Auberdine Moonwell" },
	{ 704, "Blackwood Furbolg North Bonfire" },
	{ 705, "Cliffspring River Waterfall" },
	{ 723, "Fire Plume Ridge Hot Spot" },
	{ 743, "Urok's Tribute Pile" },
	{ 763, "Andorhal Silo Temporal Rift" },
	{ 783, "Stone of Shy-Rotam" },
	{ 803, "Sacred Fire of Life" },
	{ 804, "Scarlet Crusade Forward Camp" },
	{ 805, "Andorhal Tower" },
	{ 823, "Scholomance Viewing Room" },
	{ 843, "the Jaedenar Corrupt Moon Well" },
	{ 863, "Umi's Friend" },
	{ 883, "Moonwell" },
	{ 903, "Fire Plume Ridge Lava Lake" },
	{ 923, "the crate in the center of the Northridge Lumber Mill" },
	{ 943, "Moonkin Stone" },
	{ 944, "Darrowshire Town Square" },
	{ 963, "Bright Light Beam" },
	{ 983, "Mark of Detonation" },
	{ 1003, "Cliffspring Falls Cave Mouth" },
	{ 1004, "Dreadmist Peak Pool" },
	{ 1023, "The Dead Goliaths" },
	{ 1043, "Shrine of Remulos" },
	{ 1063, "Foulweald Totem Mound" },
	{ 1083, "Dire Pool" },
	{ 1103, "Maraudon Portal" },
	{ 1123, "Horde Globe of Scrying" },
	{ 1143, "Eastern Crater" },
	{ 1144, "Western Crater" },
	{ 1145, "Snowfall Graveyard" },
	{ 1163, "Alliance Globe of Scrying" },
	{ 1164, "Dun Baldar Courtyard" },
	{ 1165, "Frostwolf Keep Courtyard" },
	{ 1183, "Snowfall Graveyard" },
	{ 1184, "East Crater" },
	{ 1185, "West Crater" },
	{ 1203, "Orange Crystal Pool" },
	{ 1223, "Onyxia's Flame Breath" },
	{ 1243, "Kroshius' Remains" },
	{ 1263, "Pedestal of Immol'thar" },
	{ 1264, "Circle of Dark Summoning" },
	{ 1283, "The Great Ossuary" },
	{ 1284, "Terrordale Haunting Spirit" },
	{ 1303, "Aerie Peak Town Center" },
	{ 1323, "Uther's Tomb Statue" },
	{ 1324, "Grom's Monument" },
	{ 1343, "Pagle's Pointe" },
	{ 1344, "Altar of Zanza" },
	{ 1345, "Southshore" },
	{ 1346, "Bones of Grakkarond" },
	{ 1347, "Forsaken Stink Bomb" },
	{ 1348, "Drop-Off Point" },
	{ 1349, "Swirling Maelstrom" },
	{ 1350, "High Chief Winterfall's Cave" },
	{ 1351, "Firework Launcher" },
	{ 1352, "Cluster Launcher" },
	{ 1353, "Greater Moonlight" },
	{ 1354, "Voone's Chamber" },
	{ 1355, "Alzzin's Chamber" },
	{ 1356, "The Crimson Throne" },
	{ 1357, "Ras Frostwhisper's Chamber" },
	{ 1358, "The Beast's Chamber" },
	{ 1359, "Haunted Locus" },
	{ 1360, "Blackrock Depths Arena" },
	{ 1361, "[PH] Crystal Corpse" },
	{ 1362, "Icebellow Anvil" },
	{ 1364, "Consecrated Earth" },
	{ 1365, "Midsummer Bonfire" },
	{ 1366, "Maypole" },
}
